import { test, expect } from '@playwright/test';
import path from 'path';

test.describe('Playlist_pic Authed Features (Saving & Playback)', () => {
  const targetUrl = 'http://127.0.0.1:3000';
  const sampleImagePath = path.resolve('tests/assets/beach.png');

  test.beforeEach(async ({ context }) => {
    // Inject the session cookie for 'test_user_id' which was seeded by server.js in test mode
    await context.addCookies([{
      name: 'spotify_user_id',
      value: 'test_user_id',
      url: targetUrl
    }]);
  });

  test('should display user panel with logged in status and show custom save modal on save click', async ({ page }) => {
    // 1. Navigate to dashboard
    await page.goto(targetUrl);
    await expect(page).toHaveTitle(/Moment.AI/);

    // Verify user info is visible (indicating logged in status)
    const userPanel = page.locator('#userPanel');
    await expect(userPanel).toContainText('Test User');

    // 2. Upload image and generate playlist
    const fileInput = page.locator('#fileInput');
    await fileInput.setInputFiles(sampleImagePath);

    const generateBtn = page.locator('#btnGeneratePlaylist');
    await expect(generateBtn).toBeVisible();
    await generateBtn.click();

    // Wait for analysis to complete
    await expect(page.locator('#analysisCard')).toBeVisible();
    await page.waitForSelector('#analysisLoader', { state: 'hidden', timeout: 30000 });

    // 3. Verify that the Save button is visible
    const saveBtn = page.locator('#btnSavePlaylist');
    await expect(saveBtn).toBeVisible();
    await expect(saveBtn).toContainText('Save Playlist to Spotify');

    // 4. Click Save Playlist - should open our custom modal
    await saveBtn.click();

    const saveModal = page.locator('#savePlaylistModal');
    await expect(saveModal).toBeVisible();

    // Verify inputs in modal are prefilled
    const nameInput = page.locator('#modalPlaylistName');
    const descInput = page.locator('#modalPlaylistDescription');
    const privacyPublic = page.locator('#privacyPublic');
    const uploadCoverCheck = page.locator('#modalUploadCover');

    await expect(nameInput).toHaveValue(/Moment.AI/);
    await expect(descInput).toHaveValue(/Generated by Moment.AI/);
    await expect(privacyPublic).toBeChecked();
    await expect(uploadCoverCheck).toBeChecked();

    // 5. Fill in new playlist details
    await nameInput.fill('My Custom Test Vibe');
    await descInput.fill('This is a custom test description.');
    await page.locator('#privacyPrivate').check();

    // 6. Click Export to Spotify
    const confirmSaveBtn = page.locator('#btnConfirmSave');
    await confirmSaveBtn.click();

    // Save modal should close, success modal should open
    await expect(saveModal).toBeHidden();

    const successModal = page.locator('#successModal');
    await expect(successModal).toBeVisible();
    await expect(page.locator('#successModalText')).toContainText('My Custom Test Vibe');

    // Verify Open in Spotify link is loaded with mock URL
    const openSpotifyLink = page.locator('#linkOpenSpotify');
    await expect(openSpotifyLink).toHaveAttribute('href', 'https://open.spotify.com/playlist/mock_playlist_123');

    // 7. Close Success Modal
    await page.click('#btnSuccessCloseAction');
    await expect(successModal).toBeHidden();
  });

  test('should load spotify playback widget when a track is clicked', async ({ page }) => {
    // 1. Navigate to dashboard
    await page.goto(targetUrl);

    // 2. Upload image and generate playlist
    const fileInput = page.locator('#fileInput');
    await fileInput.setInputFiles(sampleImagePath);

    const generateBtn = page.locator('#btnGeneratePlaylist');
    await generateBtn.click();
    await page.waitForSelector('#analysisLoader', { state: 'hidden', timeout: 30000 });

    // 3. Verify no player widget is loaded initially
    const playerContainer = page.locator('#spotifyPlayerContainer');
    await expect(playerContainer).toBeHidden();

    // 4. Click on the first track card to load player
    const firstTrack = page.locator('.track-card').first();
    await expect(firstTrack).toBeVisible();
    
    // Get track ID from the card element
    const trackIdAttr = await firstTrack.getAttribute('id');
    const trackId = trackIdAttr.replace('track-', '');

    // Click track
    await firstTrack.locator('.track-main-info').click();

    // 5. Verify track card becomes active
    await expect(firstTrack).toHaveClass(/active/);

    // 6. Verify Spotify Player Embed is loaded and visible
    await expect(playerContainer).toBeVisible();
    
    const customPlayer = playerContainer.locator('.custom-audio-player');
    const volumeSlider = playerContainer.locator('#previewVolumeSlider');
    await expect(customPlayer).toBeVisible();
    await expect(volumeSlider).toBeVisible();

    // 7. Click active track card again - should close player
    await firstTrack.locator('.track-main-info').click();
    await expect(firstTrack).not.toHaveClass(/active/);
    await expect(playerContainer).toBeHidden();
  });

  test('should detect visible artist and interleave with custom prompt tracks 50/50', async ({ page }) => {
    // 1. Navigate to dashboard
    await page.goto(targetUrl);

    // 2. Upload image and set custom prompt to trigger artist-mode mocking
    const fileInput = page.locator('#fileInput');
    await fileInput.setInputFiles(sampleImagePath);

    // Enter 'artist-mode' in the custom prompt input
    const promptInput = page.locator('#customTextPrompt');
    await promptInput.fill('artist-mode');

    const generateBtn = page.locator('#btnGeneratePlaylist');
    await generateBtn.click();
    await page.waitForSelector('#analysisLoader', { state: 'hidden', timeout: 30000 });

    // 3. Verify artist top tracks (Pool A) and search tracks (Pool B) are present
    // According to our mock:
    // Pool A (Billie Eilish): "Mock Song 1 by Billie Eilish", "Mock Song 2 by Billie Eilish"
    // Pool B (search for "artist-mode"): "Mock Search Song 1 for "artist-mode"", etc.
    // They are interleaved 50/50:
    // Track 1: Pool A Track 1 ("Mock Song 1 by Billie Eilish")
    // Track 2: Pool B Track 1 ("Mock Search Song 1 for \"artist-mode\"")
    // Track 3: Pool A Track 2 ("Mock Song 2 by Billie Eilish")
    // Track 4: Pool B Track 2 ("Mock Search Song 2 for \"artist-mode\"")

    const trackCards = page.locator('.track-card');
    await expect(trackCards).toHaveCount(4); // 2 artist + 2 search tracks interleaved

    const track1Text = await trackCards.nth(0).locator('.track-title').textContent();
    const track2Text = await trackCards.nth(1).locator('.track-title').textContent();
    const track3Text = await trackCards.nth(2).locator('.track-title').textContent();
    const track4Text = await trackCards.nth(3).locator('.track-title').textContent();

    expect(track1Text).toContain('Mock Song 1 by Billie Eilish');
    expect(track2Text).toContain('Mock Search Song 1 for "artist-mode"');
    expect(track3Text).toContain('Mock Song 2 by Billie Eilish');
    expect(track4Text).toContain('Mock Search Song 2 for "artist-mode"');
  });
});
