import { test, expect } from '@playwright/test';
import path from 'path';

test.describe('Playlist_pic Authed Features (Saving & Playback)', () => {
  const targetUrl = 'http://127.0.0.1:3000';
  const sampleImagePath = path.resolve('tests/assets/beach.png');

  test.beforeEach(async ({ page }) => {
    // Intercept Supabase config fetch to ensure it returns mock config in test mode
    await page.route('**/api/auth/config', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          supabaseUrl: 'https://bonebcazubomgwuirwfr.supabase.co',
          supabaseAnonKey: 'mock_anon_key'
        })
      });
    });

    // Intercept Supabase Auth SignIn request
    await page.route('**/auth/v1/token?grant_type=password', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          access_token: 'test_token',
          token_type: 'bearer',
          expires_in: 3600,
          refresh_token: 'mock_refresh_token',
          user: {
            id: 'test_user_id',
            email: 'test@example.com',
            user_metadata: { full_name: 'Test User' },
            app_metadata: { provider: 'email' }
          }
        })
      });
    });

    // Intercept Supabase Auth getSession / user lookup requests
    await page.route('**/auth/v1/user', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          id: 'test_user_id',
          email: 'test@example.com',
          user_metadata: { full_name: 'Test User' },
          app_metadata: { provider: 'email' }
        })
      });
    });

    // Perform Login
    await page.goto(targetUrl);
    const signInBtn = page.locator('#btnSignIn');
    await expect(signInBtn).toBeVisible();
    await signInBtn.click();
    await page.locator('#authEmail').fill('test@example.com');
    await page.locator('#authPassword').fill('password123');
    await page.locator('#btnSubmitAuth').click();

    // Verify user info is visible in header to ensure logged-in state is active before proceeding
    const userPanel = page.locator('#userPanel');
    await expect(userPanel).toContainText('Test User');
  });

  test('should generate tracks and save playlist', async ({ page }) => {
    // 1. Upload image and generate playlist
    const fileInput = page.locator('#fileInput');
    await fileInput.setInputFiles(sampleImagePath);

    const generateBtn = page.locator('#btnGeneratePlaylist');
    await expect(generateBtn).toBeVisible();
    await generateBtn.click();

    // Wait for analysis to complete (covers long Spotify resolve + retries)
    await expect(page.locator('#analysisCard')).toBeVisible({ timeout: 60000 });
    await page.waitForSelector('#analysisLoader', { state: 'hidden', timeout: 90000 });

    // Playlist must be populated before export
    const trackCards = page.locator('#tracklistContainer .track-card');
    await expect(trackCards.first()).toBeVisible({ timeout: 15000 });
    expect(await trackCards.count()).toBeGreaterThan(0);

    // 2. Verify that the Save button is visible
    const saveBtn = page.locator('#btnSavePlaylist');
    await expect(saveBtn).toBeVisible({ timeout: 15000 });
    await expect(saveBtn).toContainText(/Save .*Spotify/i);

    // 3. Click Save Playlist - should open our custom modal
    await saveBtn.click();

    const saveModal = page.locator('#savePlaylistModal');
    await expect(saveModal).toBeVisible();

    // Verify inputs in modal are prefilled
    const nameInput = page.locator('#modalPlaylistName');
    const descInput = page.locator('#modalPlaylistDescription');
    const uploadCoverCheck = page.locator('#modalUploadCover');

    await expect(nameInput).toHaveValue(/Moment.AI/);
    await expect(descInput).toHaveValue(/Generated by Moment.AI/);
    await expect(uploadCoverCheck).toBeChecked();

    // Fill in new playlist details
    await nameInput.fill('My Custom Test Vibe');
    await descInput.fill('This is a custom test description.');

    // 4. Click Export to Spotify
    const confirmSaveBtn = page.locator('#btnConfirmSave');
    await confirmSaveBtn.click();

    // Save modal should close, success modal should open
    await expect(saveModal).toBeHidden();

    const successModal = page.locator('#successModal');
    await expect(successModal).toBeVisible();
    await expect(page.locator('#successModalText')).toContainText('My Custom Test Vibe');

    // Verify Open in Spotify link is loaded with mock URL
    const openSpotifyLink = page.locator('#linkOpenSpotify');
    await expect(openSpotifyLink).toHaveAttribute('href', 'https://open.spotify.com/playlist/mock_playlist_123');

    // 5. Close Success Modal
    await page.click('#btnSuccessCloseAction');
    await expect(successModal).toBeHidden();
  });

  test('should load player widget when a track is clicked', async ({ page }) => {
    // 1. Upload image and generate playlist
    const fileInput = page.locator('#fileInput');
    await fileInput.setInputFiles(sampleImagePath);

    const generateBtn = page.locator('#btnGeneratePlaylist');
    await expect(generateBtn).toBeVisible();
    await generateBtn.click();
    await page.waitForSelector('#analysisLoader', { state: 'hidden', timeout: 90000 });

    // 2. Verify no player widget is loaded initially
    const playerContainer = page.locator('#spotifyPlayerContainer');
    await expect(playerContainer).toBeHidden();

    // 3. Click on the first track card to load player
    const firstTrack = page.locator('#tracklistContainer .track-card').first();
    await expect(firstTrack).toBeVisible();
    
    // Click track
    await firstTrack.locator('.track-main-info').click();

    // 4. Verify track card becomes active
    await expect(firstTrack).toHaveClass(/active/);

    // 5. Verify Spotify Player Embed is loaded and visible
    await expect(playerContainer).toBeVisible();
    
    const customPlayer = playerContainer.locator('.custom-audio-player');
    const volumeSlider = playerContainer.locator('#previewVolumeSlider');
    await expect(customPlayer).toBeVisible();
    await expect(volumeSlider).toBeVisible();

    // 6. Click active track card again - should close player
    await firstTrack.locator('.track-main-info').click();
    await expect(firstTrack).not.toHaveClass(/active/);
    await expect(playerContainer).toBeHidden();
  });
});
